// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// RepresenrService is an autogenerated mock type for the RepresenrService type
type RepresenrService struct {
	mock.Mock
}

// Home provides a mock function with given fields: _a0
func (_m *RepresenrService) Home(_a0 http.ResponseWriter) {
	_m.Called(_a0)
}

// NewRepresenrService creates a new instance of RepresenrService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepresenrService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepresenrService {
	mock := &RepresenrService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
